APP: apiServer #项目名称
ENV: dev   #当前环境 开发dev 测试test 生产pro
Debug: true #是否开启debug模式
LogFileName: apiServer #日志文件名称
LogPath: logs #日志文件目录
LogLevel: TRAC #日志等级
JwtSecret: b068b9a9147332cc0f679cb876f43ded017820974c7b87d02e3e339195a8267c
Http:
    Port: 8001
Mysql:
    -
        Host: 192.168.77.106
        Port: 3306
        User: new_vchat
        Password: weisheng@123
        Database: v_chat
        Name: master #主库
    -
        Host: 192.168.77.106
        Port: 3306
        User: new_vchat
        Password: weisheng@123
        Database: v_chat
        Name: slave #从库
Pgsql:
    -
        Host: 192.168.77.107
        Port: 5432
        User: postgres
        Password: weisheng@123#pg
        Database: v_chat
        Name: default
Redis:
    -
        Host: 192.168.77.108
        Port: 6379
        Password: tdhRY9s
        Database: 0
        Name: user #用户相关
    -
        Host: 192.168.77.108
        Port: 6379
        Password: tdhRY9s
        Database: 1
        Name: chatroom #聊天室相关
    -
        Host: 192.168.77.108
        Port: 6379
        Password: tdhRY9s
        Database: 2
        Name: im #队列相关
Kafka:
    Action:
        Addr:
            - 192.168.77.109:9092
        Topic: action
    Gift:
        Addr:
            - 192.168.77.109:9092
        Topic: gift
    PrivateChat:
        Addr:
            - 192.168.77.109:9092
        Topic: private_chat
    PublicChat:
        Addr:
            - 192.168.77.109:9092
        Topic: public_chat
InnerIp:
    - 192.168.77.10
    - 192.168.77.115
    - 192.168.77.113
    - 192.168.77.114