APP: ori #项目名称
ENV: dev   #当前环境 开发dev 测试test 生产pro
Debug: true #是否开启debug模式
LogFileName: ori #日志文件名称
LogPath: logs #日志文件目录
LogLevel: TRAC #日志等级
Websocket:
  Port: 9002
Http:
  Port: 9001
Mysql:
  -
    Host: 127.0.0.1
    Port: 3306
    User: root
    Password: root
    Database: test
    Name: default
Redis:
  -
    Host: 127.0.0.1
    Port: 6379
    Password:
    Database: 0
    Name: default